# Generated by Django 4.0.6 on 2023-01-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='course_code',
            field=models.CharField(max_length=100),
        ),
    ]
