# Generated by Django 4.0.6 on 2023-01-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_intern_course_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intern',
            new_name='Courses',
        ),
    ]
