# Generated by Django 4.0.6 on 2023-01-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_intern_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='building',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='capacity',
            field=models.IntegerField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='class_rest',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='enrolled',
            field=models.IntegerField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='instructor',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='major_restriction',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='prerequisites',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='room',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='teaching_method',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
