# Generated by Django 4.1.5 on 2023-01-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_courses_building_alter_courses_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='capacity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='crn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='enrolled',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
