# Generated by Django 4.1.5 on 2023-01-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_courses_capacity_alter_courses_crn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='day',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='start_time',
        ),
        migrations.AddField(
            model_name='courses',
            name='day_hour',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
